
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Container } from "@mui/material";
import Header from "@/app/header/header";
import Providers from "@/app/providers";
import authenticated from "@/app/auth/authenticated";
import logout from "@/app/auth/logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isAuthenticated = await authenticated()

  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers authenticated={isAuthenticated}>
          <Header logout={logout}/>
          <Container maxWidth="lg">
            {children}
          </Container>
          </Providers>
      </body>
    </html>
  );
}